// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/payment.proto

package paymentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreatePaymentOrderRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MerchantCode    string                 `protobuf:"bytes,1,opt,name=merchant_code,json=merchantCode,proto3" json:"merchant_code,omitempty"`
	MerchantOrderId string                 `protobuf:"bytes,2,opt,name=merchant_order_id,json=merchantOrderId,proto3" json:"merchant_order_id,omitempty"`
	// payer_user_id is optional payer/actor metadata; tenant_id is the order owner.
	PayerUserId      string  `protobuf:"bytes,3,opt,name=payer_user_id,json=payerUserId,proto3" json:"payer_user_id,omitempty"`
	OrderAmount      float64 `protobuf:"fixed64,4,opt,name=order_amount,json=orderAmount,proto3" json:"order_amount,omitempty"`
	OrderCurrency    string  `protobuf:"bytes,5,opt,name=order_currency,json=orderCurrency,proto3" json:"order_currency,omitempty"`
	PaymentCurrency  string  `protobuf:"bytes,7,opt,name=payment_currency,json=paymentCurrency,proto3" json:"payment_currency,omitempty"`
	ChannelCode      string  `protobuf:"bytes,11,opt,name=channel_code,json=channelCode,proto3" json:"channel_code,omitempty"`
	IdempotencyKey   string  `protobuf:"bytes,14,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	MetadataJson     string  `protobuf:"bytes,16,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`
	SuccessReturnUrl string  `protobuf:"bytes,17,opt,name=success_return_url,json=successReturnUrl,proto3" json:"success_return_url,omitempty"`
	TenantId         string  `protobuf:"bytes,18,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreatePaymentOrderRequest) Reset() {
	*x = CreatePaymentOrderRequest{}
	mi := &file_proto_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentOrderRequest) ProtoMessage() {}

func (x *CreatePaymentOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentOrderRequest.ProtoReflect.Descriptor instead.
func (*CreatePaymentOrderRequest) Descriptor() ([]byte, []int) {
	return file_proto_payment_proto_rawDescGZIP(), []int{0}
}

func (x *CreatePaymentOrderRequest) GetMerchantCode() string {
	if x != nil {
		return x.MerchantCode
	}
	return ""
}

func (x *CreatePaymentOrderRequest) GetMerchantOrderId() string {
	if x != nil {
		return x.MerchantOrderId
	}
	return ""
}

func (x *CreatePaymentOrderRequest) GetPayerUserId() string {
	if x != nil {
		return x.PayerUserId
	}
	return ""
}

func (x *CreatePaymentOrderRequest) GetOrderAmount() float64 {
	if x != nil {
		return x.OrderAmount
	}
	return 0
}

func (x *CreatePaymentOrderRequest) GetOrderCurrency() string {
	if x != nil {
		return x.OrderCurrency
	}
	return ""
}

func (x *CreatePaymentOrderRequest) GetPaymentCurrency() string {
	if x != nil {
		return x.PaymentCurrency
	}
	return ""
}

func (x *CreatePaymentOrderRequest) GetChannelCode() string {
	if x != nil {
		return x.ChannelCode
	}
	return ""
}

func (x *CreatePaymentOrderRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *CreatePaymentOrderRequest) GetMetadataJson() string {
	if x != nil {
		return x.MetadataJson
	}
	return ""
}

func (x *CreatePaymentOrderRequest) GetSuccessReturnUrl() string {
	if x != nil {
		return x.SuccessReturnUrl
	}
	return ""
}

func (x *CreatePaymentOrderRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type GetPaymentOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentOrderRequest) Reset() {
	*x = GetPaymentOrderRequest{}
	mi := &file_proto_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentOrderRequest) ProtoMessage() {}

func (x *GetPaymentOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentOrderRequest.ProtoReflect.Descriptor instead.
func (*GetPaymentOrderRequest) Descriptor() ([]byte, []int) {
	return file_proto_payment_proto_rawDescGZIP(), []int{1}
}

func (x *GetPaymentOrderRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetPaymentOrderByMerchantOrderRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MerchantCode    string                 `protobuf:"bytes,1,opt,name=merchant_code,json=merchantCode,proto3" json:"merchant_code,omitempty"`
	MerchantOrderId string                 `protobuf:"bytes,2,opt,name=merchant_order_id,json=merchantOrderId,proto3" json:"merchant_order_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetPaymentOrderByMerchantOrderRequest) Reset() {
	*x = GetPaymentOrderByMerchantOrderRequest{}
	mi := &file_proto_payment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentOrderByMerchantOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentOrderByMerchantOrderRequest) ProtoMessage() {}

func (x *GetPaymentOrderByMerchantOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentOrderByMerchantOrderRequest.ProtoReflect.Descriptor instead.
func (*GetPaymentOrderByMerchantOrderRequest) Descriptor() ([]byte, []int) {
	return file_proto_payment_proto_rawDescGZIP(), []int{2}
}

func (x *GetPaymentOrderByMerchantOrderRequest) GetMerchantCode() string {
	if x != nil {
		return x.MerchantCode
	}
	return ""
}

func (x *GetPaymentOrderByMerchantOrderRequest) GetMerchantOrderId() string {
	if x != nil {
		return x.MerchantOrderId
	}
	return ""
}

type CheckPaymentOrderByPaymentNoRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PaymentNo       string                 `protobuf:"bytes,1,opt,name=payment_no,json=paymentNo,proto3" json:"payment_no,omitempty"`
	MerchantCode    string                 `protobuf:"bytes,2,opt,name=merchant_code,json=merchantCode,proto3" json:"merchant_code,omitempty"`
	MerchantOrderId string                 `protobuf:"bytes,3,opt,name=merchant_order_id,json=merchantOrderId,proto3" json:"merchant_order_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CheckPaymentOrderByPaymentNoRequest) Reset() {
	*x = CheckPaymentOrderByPaymentNoRequest{}
	mi := &file_proto_payment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckPaymentOrderByPaymentNoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPaymentOrderByPaymentNoRequest) ProtoMessage() {}

func (x *CheckPaymentOrderByPaymentNoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPaymentOrderByPaymentNoRequest.ProtoReflect.Descriptor instead.
func (*CheckPaymentOrderByPaymentNoRequest) Descriptor() ([]byte, []int) {
	return file_proto_payment_proto_rawDescGZIP(), []int{3}
}

func (x *CheckPaymentOrderByPaymentNoRequest) GetPaymentNo() string {
	if x != nil {
		return x.PaymentNo
	}
	return ""
}

func (x *CheckPaymentOrderByPaymentNoRequest) GetMerchantCode() string {
	if x != nil {
		return x.MerchantCode
	}
	return ""
}

func (x *CheckPaymentOrderByPaymentNoRequest) GetMerchantOrderId() string {
	if x != nil {
		return x.MerchantOrderId
	}
	return ""
}

type CheckPaymentOrderByPaymentNoResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Order          *PaymentOrderResponse  `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	Result         string                 `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	NextEligibleAt string                 `protobuf:"bytes,3,opt,name=next_eligible_at,json=nextEligibleAt,proto3" json:"next_eligible_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CheckPaymentOrderByPaymentNoResponse) Reset() {
	*x = CheckPaymentOrderByPaymentNoResponse{}
	mi := &file_proto_payment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckPaymentOrderByPaymentNoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPaymentOrderByPaymentNoResponse) ProtoMessage() {}

func (x *CheckPaymentOrderByPaymentNoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPaymentOrderByPaymentNoResponse.ProtoReflect.Descriptor instead.
func (*CheckPaymentOrderByPaymentNoResponse) Descriptor() ([]byte, []int) {
	return file_proto_payment_proto_rawDescGZIP(), []int{4}
}

func (x *CheckPaymentOrderByPaymentNoResponse) GetOrder() *PaymentOrderResponse {
	if x != nil {
		return x.Order
	}
	return nil
}

func (x *CheckPaymentOrderByPaymentNoResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *CheckPaymentOrderByPaymentNoResponse) GetNextEligibleAt() string {
	if x != nil {
		return x.NextEligibleAt
	}
	return ""
}

type ListPaymentOrdersRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Page         int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize     int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	MerchantCode string                 `protobuf:"bytes,3,opt,name=merchant_code,json=merchantCode,proto3" json:"merchant_code,omitempty"`
	// payer_user_id filters optional payer/actor metadata, not owner scope.
	PayerUserId   string `protobuf:"bytes,4,opt,name=payer_user_id,json=payerUserId,proto3" json:"payer_user_id,omitempty"`
	Status        string `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	TenantId      string `protobuf:"bytes,6,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPaymentOrdersRequest) Reset() {
	*x = ListPaymentOrdersRequest{}
	mi := &file_proto_payment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPaymentOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPaymentOrdersRequest) ProtoMessage() {}

func (x *ListPaymentOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPaymentOrdersRequest.ProtoReflect.Descriptor instead.
func (*ListPaymentOrdersRequest) Descriptor() ([]byte, []int) {
	return file_proto_payment_proto_rawDescGZIP(), []int{5}
}

func (x *ListPaymentOrdersRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListPaymentOrdersRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListPaymentOrdersRequest) GetMerchantCode() string {
	if x != nil {
		return x.MerchantCode
	}
	return ""
}

func (x *ListPaymentOrdersRequest) GetPayerUserId() string {
	if x != nil {
		return x.PayerUserId
	}
	return ""
}

func (x *ListPaymentOrdersRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListPaymentOrdersRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type ListPaymentOrdersResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Items         []*PaymentOrderResponse `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         int64                   `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                   `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                   `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPaymentOrdersResponse) Reset() {
	*x = ListPaymentOrdersResponse{}
	mi := &file_proto_payment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPaymentOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPaymentOrdersResponse) ProtoMessage() {}

func (x *ListPaymentOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPaymentOrdersResponse.ProtoReflect.Descriptor instead.
func (*ListPaymentOrdersResponse) Descriptor() ([]byte, []int) {
	return file_proto_payment_proto_rawDescGZIP(), []int{6}
}

func (x *ListPaymentOrdersResponse) GetItems() []*PaymentOrderResponse {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListPaymentOrdersResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListPaymentOrdersResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListPaymentOrdersResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListSupportedCurrenciesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSupportedCurrenciesRequest) Reset() {
	*x = ListSupportedCurrenciesRequest{}
	mi := &file_proto_payment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSupportedCurrenciesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSupportedCurrenciesRequest) ProtoMessage() {}

func (x *ListSupportedCurrenciesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSupportedCurrenciesRequest.ProtoReflect.Descriptor instead.
func (*ListSupportedCurrenciesRequest) Descriptor() ([]byte, []int) {
	return file_proto_payment_proto_rawDescGZIP(), []int{7}
}

type ListSupportedCurrenciesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Currencies    []string               `protobuf:"bytes,1,rep,name=currencies,proto3" json:"currencies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSupportedCurrenciesResponse) Reset() {
	*x = ListSupportedCurrenciesResponse{}
	mi := &file_proto_payment_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSupportedCurrenciesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSupportedCurrenciesResponse) ProtoMessage() {}

func (x *ListSupportedCurrenciesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSupportedCurrenciesResponse.ProtoReflect.Descriptor instead.
func (*ListSupportedCurrenciesResponse) Descriptor() ([]byte, []int) {
	return file_proto_payment_proto_rawDescGZIP(), []int{8}
}

func (x *ListSupportedCurrenciesResponse) GetCurrencies() []string {
	if x != nil {
		return x.Currencies
	}
	return nil
}

type ListAvailablePaymentChannelsRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MerchantCode    string                 `protobuf:"bytes,1,opt,name=merchant_code,json=merchantCode,proto3" json:"merchant_code,omitempty"`
	OrderAmount     float64                `protobuf:"fixed64,2,opt,name=order_amount,json=orderAmount,proto3" json:"order_amount,omitempty"`
	OrderCurrency   string                 `protobuf:"bytes,3,opt,name=order_currency,json=orderCurrency,proto3" json:"order_currency,omitempty"`
	PaymentCurrency string                 `protobuf:"bytes,4,opt,name=payment_currency,json=paymentCurrency,proto3" json:"payment_currency,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListAvailablePaymentChannelsRequest) Reset() {
	*x = ListAvailablePaymentChannelsRequest{}
	mi := &file_proto_payment_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAvailablePaymentChannelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAvailablePaymentChannelsRequest) ProtoMessage() {}

func (x *ListAvailablePaymentChannelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAvailablePaymentChannelsRequest.ProtoReflect.Descriptor instead.
func (*ListAvailablePaymentChannelsRequest) Descriptor() ([]byte, []int) {
	return file_proto_payment_proto_rawDescGZIP(), []int{9}
}

func (x *ListAvailablePaymentChannelsRequest) GetMerchantCode() string {
	if x != nil {
		return x.MerchantCode
	}
	return ""
}

func (x *ListAvailablePaymentChannelsRequest) GetOrderAmount() float64 {
	if x != nil {
		return x.OrderAmount
	}
	return 0
}

func (x *ListAvailablePaymentChannelsRequest) GetOrderCurrency() string {
	if x != nil {
		return x.OrderCurrency
	}
	return ""
}

func (x *ListAvailablePaymentChannelsRequest) GetPaymentCurrency() string {
	if x != nil {
		return x.PaymentCurrency
	}
	return ""
}

type AvailablePaymentChannel struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ChannelCode     string                 `protobuf:"bytes,1,opt,name=channel_code,json=channelCode,proto3" json:"channel_code,omitempty"`
	Name            string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	PaymentCurrency string                 `protobuf:"bytes,6,opt,name=payment_currency,json=paymentCurrency,proto3" json:"payment_currency,omitempty"`
	PaymentAmount   float64                `protobuf:"fixed64,7,opt,name=payment_amount,json=paymentAmount,proto3" json:"payment_amount,omitempty"`
	Category        string                 `protobuf:"bytes,10,opt,name=category,proto3" json:"category,omitempty"`
	CategoryName    string                 `protobuf:"bytes,11,opt,name=category_name,json=categoryName,proto3" json:"category_name,omitempty"`
	CategoryOrder   int32                  `protobuf:"varint,13,opt,name=category_order,json=categoryOrder,proto3" json:"category_order,omitempty"`
	MethodOrder     int32                  `protobuf:"varint,14,opt,name=method_order,json=methodOrder,proto3" json:"method_order,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AvailablePaymentChannel) Reset() {
	*x = AvailablePaymentChannel{}
	mi := &file_proto_payment_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AvailablePaymentChannel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvailablePaymentChannel) ProtoMessage() {}

func (x *AvailablePaymentChannel) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvailablePaymentChannel.ProtoReflect.Descriptor instead.
func (*AvailablePaymentChannel) Descriptor() ([]byte, []int) {
	return file_proto_payment_proto_rawDescGZIP(), []int{10}
}

func (x *AvailablePaymentChannel) GetChannelCode() string {
	if x != nil {
		return x.ChannelCode
	}
	return ""
}

func (x *AvailablePaymentChannel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AvailablePaymentChannel) GetPaymentCurrency() string {
	if x != nil {
		return x.PaymentCurrency
	}
	return ""
}

func (x *AvailablePaymentChannel) GetPaymentAmount() float64 {
	if x != nil {
		return x.PaymentAmount
	}
	return 0
}

func (x *AvailablePaymentChannel) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *AvailablePaymentChannel) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

func (x *AvailablePaymentChannel) GetCategoryOrder() int32 {
	if x != nil {
		return x.CategoryOrder
	}
	return 0
}

func (x *AvailablePaymentChannel) GetMethodOrder() int32 {
	if x != nil {
		return x.MethodOrder
	}
	return 0
}

type ListAvailablePaymentChannelsResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Items         []*AvailablePaymentChannel `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAvailablePaymentChannelsResponse) Reset() {
	*x = ListAvailablePaymentChannelsResponse{}
	mi := &file_proto_payment_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAvailablePaymentChannelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAvailablePaymentChannelsResponse) ProtoMessage() {}

func (x *ListAvailablePaymentChannelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAvailablePaymentChannelsResponse.ProtoReflect.Descriptor instead.
func (*ListAvailablePaymentChannelsResponse) Descriptor() ([]byte, []int) {
	return file_proto_payment_proto_rawDescGZIP(), []int{11}
}

func (x *ListAvailablePaymentChannelsResponse) GetItems() []*AvailablePaymentChannel {
	if x != nil {
		return x.Items
	}
	return nil
}

type PaymentOrderResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PaymentNo       string                 `protobuf:"bytes,2,opt,name=payment_no,json=paymentNo,proto3" json:"payment_no,omitempty"`
	MerchantCode    string                 `protobuf:"bytes,3,opt,name=merchant_code,json=merchantCode,proto3" json:"merchant_code,omitempty"`
	MerchantOrderId string                 `protobuf:"bytes,4,opt,name=merchant_order_id,json=merchantOrderId,proto3" json:"merchant_order_id,omitempty"`
	// payer_user_id is optional payer/actor metadata; tenant_id is the order owner.
	PayerUserId         string  `protobuf:"bytes,5,opt,name=payer_user_id,json=payerUserId,proto3" json:"payer_user_id,omitempty"`
	OrderAmount         float64 `protobuf:"fixed64,6,opt,name=order_amount,json=orderAmount,proto3" json:"order_amount,omitempty"`
	OrderCurrency       string  `protobuf:"bytes,7,opt,name=order_currency,json=orderCurrency,proto3" json:"order_currency,omitempty"`
	SettlementAmount    float64 `protobuf:"fixed64,8,opt,name=settlement_amount,json=settlementAmount,proto3" json:"settlement_amount,omitempty"`
	SettlementCurrency  string  `protobuf:"bytes,9,opt,name=settlement_currency,json=settlementCurrency,proto3" json:"settlement_currency,omitempty"`
	PaymentAmount       float64 `protobuf:"fixed64,10,opt,name=payment_amount,json=paymentAmount,proto3" json:"payment_amount,omitempty"`
	PaymentCurrency     string  `protobuf:"bytes,11,opt,name=payment_currency,json=paymentCurrency,proto3" json:"payment_currency,omitempty"`
	OrderExchangeRate   float64 `protobuf:"fixed64,12,opt,name=order_exchange_rate,json=orderExchangeRate,proto3" json:"order_exchange_rate,omitempty"`
	PaymentExchangeRate float64 `protobuf:"fixed64,13,opt,name=payment_exchange_rate,json=paymentExchangeRate,proto3" json:"payment_exchange_rate,omitempty"`
	Provider            string  `protobuf:"bytes,14,opt,name=provider,proto3" json:"provider,omitempty"`
	ChannelCode         string  `protobuf:"bytes,15,opt,name=channel_code,json=channelCode,proto3" json:"channel_code,omitempty"`
	ChannelId           uint64  `protobuf:"varint,16,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	MerchantAccountId   uint64  `protobuf:"varint,17,opt,name=merchant_account_id,json=merchantAccountId,proto3" json:"merchant_account_id,omitempty"`
	ProviderPaymentId   string  `protobuf:"bytes,18,opt,name=provider_payment_id,json=providerPaymentId,proto3" json:"provider_payment_id,omitempty"`
	CheckoutUrl         string  `protobuf:"bytes,19,opt,name=checkout_url,json=checkoutUrl,proto3" json:"checkout_url,omitempty"`
	Status              string  `protobuf:"bytes,20,opt,name=status,proto3" json:"status,omitempty"`
	FailureReason       string  `protobuf:"bytes,21,opt,name=failure_reason,json=failureReason,proto3" json:"failure_reason,omitempty"`
	MetadataJson        string  `protobuf:"bytes,22,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`
	ExpiresAt           string  `protobuf:"bytes,23,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	CreatedAt           string  `protobuf:"bytes,24,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt           string  `protobuf:"bytes,25,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	TenantId            string  `protobuf:"bytes,26,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	GatewayConnectionId uint64  `protobuf:"varint,27,opt,name=gateway_connection_id,json=gatewayConnectionId,proto3" json:"gateway_connection_id,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *PaymentOrderResponse) Reset() {
	*x = PaymentOrderResponse{}
	mi := &file_proto_payment_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentOrderResponse) ProtoMessage() {}

func (x *PaymentOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentOrderResponse.ProtoReflect.Descriptor instead.
func (*PaymentOrderResponse) Descriptor() ([]byte, []int) {
	return file_proto_payment_proto_rawDescGZIP(), []int{12}
}

func (x *PaymentOrderResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PaymentOrderResponse) GetPaymentNo() string {
	if x != nil {
		return x.PaymentNo
	}
	return ""
}

func (x *PaymentOrderResponse) GetMerchantCode() string {
	if x != nil {
		return x.MerchantCode
	}
	return ""
}

func (x *PaymentOrderResponse) GetMerchantOrderId() string {
	if x != nil {
		return x.MerchantOrderId
	}
	return ""
}

func (x *PaymentOrderResponse) GetPayerUserId() string {
	if x != nil {
		return x.PayerUserId
	}
	return ""
}

func (x *PaymentOrderResponse) GetOrderAmount() float64 {
	if x != nil {
		return x.OrderAmount
	}
	return 0
}

func (x *PaymentOrderResponse) GetOrderCurrency() string {
	if x != nil {
		return x.OrderCurrency
	}
	return ""
}

func (x *PaymentOrderResponse) GetSettlementAmount() float64 {
	if x != nil {
		return x.SettlementAmount
	}
	return 0
}

func (x *PaymentOrderResponse) GetSettlementCurrency() string {
	if x != nil {
		return x.SettlementCurrency
	}
	return ""
}

func (x *PaymentOrderResponse) GetPaymentAmount() float64 {
	if x != nil {
		return x.PaymentAmount
	}
	return 0
}

func (x *PaymentOrderResponse) GetPaymentCurrency() string {
	if x != nil {
		return x.PaymentCurrency
	}
	return ""
}

func (x *PaymentOrderResponse) GetOrderExchangeRate() float64 {
	if x != nil {
		return x.OrderExchangeRate
	}
	return 0
}

func (x *PaymentOrderResponse) GetPaymentExchangeRate() float64 {
	if x != nil {
		return x.PaymentExchangeRate
	}
	return 0
}

func (x *PaymentOrderResponse) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *PaymentOrderResponse) GetChannelCode() string {
	if x != nil {
		return x.ChannelCode
	}
	return ""
}

func (x *PaymentOrderResponse) GetChannelId() uint64 {
	if x != nil {
		return x.ChannelId
	}
	return 0
}

func (x *PaymentOrderResponse) GetMerchantAccountId() uint64 {
	if x != nil {
		return x.MerchantAccountId
	}
	return 0
}

func (x *PaymentOrderResponse) GetProviderPaymentId() string {
	if x != nil {
		return x.ProviderPaymentId
	}
	return ""
}

func (x *PaymentOrderResponse) GetCheckoutUrl() string {
	if x != nil {
		return x.CheckoutUrl
	}
	return ""
}

func (x *PaymentOrderResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PaymentOrderResponse) GetFailureReason() string {
	if x != nil {
		return x.FailureReason
	}
	return ""
}

func (x *PaymentOrderResponse) GetMetadataJson() string {
	if x != nil {
		return x.MetadataJson
	}
	return ""
}

func (x *PaymentOrderResponse) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

func (x *PaymentOrderResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *PaymentOrderResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *PaymentOrderResponse) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *PaymentOrderResponse) GetGatewayConnectionId() uint64 {
	if x != nil {
		return x.GatewayConnectionId
	}
	return 0
}

var File_proto_payment_proto protoreflect.FileDescriptor

const file_proto_payment_proto_rawDesc = "" +
	"\n" +
	"\x13proto/payment.proto\x12\n" +
	"payment.v1\"\xea\x04\n" +
	"\x19CreatePaymentOrderRequest\x12#\n" +
	"\rmerchant_code\x18\x01 \x01(\tR\fmerchantCode\x12*\n" +
	"\x11merchant_order_id\x18\x02 \x01(\tR\x0fmerchantOrderId\x12\"\n" +
	"\rpayer_user_id\x18\x03 \x01(\tR\vpayerUserId\x12!\n" +
	"\forder_amount\x18\x04 \x01(\x01R\vorderAmount\x12%\n" +
	"\x0eorder_currency\x18\x05 \x01(\tR\rorderCurrency\x12)\n" +
	"\x10payment_currency\x18\a \x01(\tR\x0fpaymentCurrency\x12!\n" +
	"\fchannel_code\x18\v \x01(\tR\vchannelCode\x12'\n" +
	"\x0fidempotency_key\x18\x0e \x01(\tR\x0eidempotencyKey\x12#\n" +
	"\rmetadata_json\x18\x10 \x01(\tR\fmetadataJson\x12,\n" +
	"\x12success_return_url\x18\x11 \x01(\tR\x10successReturnUrl\x12\x1b\n" +
	"\ttenant_id\x18\x12 \x01(\tR\btenantIdJ\x04\b\x06\x10\aJ\x04\b\b\x10\tJ\x04\b\t\x10\n" +
	"J\x04\b\n" +
	"\x10\vJ\x04\b\f\x10\rJ\x04\b\r\x10\x0eJ\x04\b\x0f\x10\x10R\x13settlement_currencyR\x13order_exchange_rateR\x15payment_exchange_rateR\bproviderR\n" +
	"channel_idR\x13merchant_account_idR\x11callback_base_url\"(\n" +
	"\x16GetPaymentOrderRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"x\n" +
	"%GetPaymentOrderByMerchantOrderRequest\x12#\n" +
	"\rmerchant_code\x18\x01 \x01(\tR\fmerchantCode\x12*\n" +
	"\x11merchant_order_id\x18\x02 \x01(\tR\x0fmerchantOrderId\"\x95\x01\n" +
	"#CheckPaymentOrderByPaymentNoRequest\x12\x1d\n" +
	"\n" +
	"payment_no\x18\x01 \x01(\tR\tpaymentNo\x12#\n" +
	"\rmerchant_code\x18\x02 \x01(\tR\fmerchantCode\x12*\n" +
	"\x11merchant_order_id\x18\x03 \x01(\tR\x0fmerchantOrderId\"\xa0\x01\n" +
	"$CheckPaymentOrderByPaymentNoResponse\x126\n" +
	"\x05order\x18\x01 \x01(\v2 .payment.v1.PaymentOrderResponseR\x05order\x12\x16\n" +
	"\x06result\x18\x02 \x01(\tR\x06result\x12(\n" +
	"\x10next_eligible_at\x18\x03 \x01(\tR\x0enextEligibleAt\"\xc9\x01\n" +
	"\x18ListPaymentOrdersRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12#\n" +
	"\rmerchant_code\x18\x03 \x01(\tR\fmerchantCode\x12\"\n" +
	"\rpayer_user_id\x18\x04 \x01(\tR\vpayerUserId\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1b\n" +
	"\ttenant_id\x18\x06 \x01(\tR\btenantId\"\x9a\x01\n" +
	"\x19ListPaymentOrdersResponse\x126\n" +
	"\x05items\x18\x01 \x03(\v2 .payment.v1.PaymentOrderResponseR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\" \n" +
	"\x1eListSupportedCurrenciesRequest\"A\n" +
	"\x1fListSupportedCurrenciesResponse\x12\x1e\n" +
	"\n" +
	"currencies\x18\x01 \x03(\tR\n" +
	"currencies\"\xbf\x01\n" +
	"#ListAvailablePaymentChannelsRequest\x12#\n" +
	"\rmerchant_code\x18\x01 \x01(\tR\fmerchantCode\x12!\n" +
	"\forder_amount\x18\x02 \x01(\x01R\vorderAmount\x12%\n" +
	"\x0eorder_currency\x18\x03 \x01(\tR\rorderCurrency\x12)\n" +
	"\x10payment_currency\x18\x04 \x01(\tR\x0fpaymentCurrency\"\x83\x04\n" +
	"\x17AvailablePaymentChannel\x12!\n" +
	"\fchannel_code\x18\x01 \x01(\tR\vchannelCode\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12)\n" +
	"\x10payment_currency\x18\x06 \x01(\tR\x0fpaymentCurrency\x12%\n" +
	"\x0epayment_amount\x18\a \x01(\x01R\rpaymentAmount\x12\x1a\n" +
	"\bcategory\x18\n" +
	" \x01(\tR\bcategory\x12#\n" +
	"\rcategory_name\x18\v \x01(\tR\fcategoryName\x12%\n" +
	"\x0ecategory_order\x18\r \x01(\x05R\rcategoryOrder\x12!\n" +
	"\fmethod_order\x18\x0e \x01(\x05R\vmethodOrderJ\x04\b\x02\x10\x03J\x04\b\x03\x10\x04J\x04\b\x04\x10\x05J\x04\b\b\x10\tJ\x04\b\t\x10\n" +
	"J\x04\b\f\x10\rJ\x04\b\x0f\x10\x10J\x04\b\x10\x10\x11J\x04\b\x11\x10\x12J\x04\b\x12\x10\x13R\bproviderR\n" +
	"channel_idR\x13merchant_account_idR\x04iconR\x11name_translationsR\x1acategory_name_translationsR\blogo_keyR\blogo_urlR\x0fname_locale_keyR\x13category_locale_key\"a\n" +
	"$ListAvailablePaymentChannelsResponse\x129\n" +
	"\x05items\x18\x01 \x03(\v2#.payment.v1.AvailablePaymentChannelR\x05items\"\x8b\b\n" +
	"\x14PaymentOrderResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1d\n" +
	"\n" +
	"payment_no\x18\x02 \x01(\tR\tpaymentNo\x12#\n" +
	"\rmerchant_code\x18\x03 \x01(\tR\fmerchantCode\x12*\n" +
	"\x11merchant_order_id\x18\x04 \x01(\tR\x0fmerchantOrderId\x12\"\n" +
	"\rpayer_user_id\x18\x05 \x01(\tR\vpayerUserId\x12!\n" +
	"\forder_amount\x18\x06 \x01(\x01R\vorderAmount\x12%\n" +
	"\x0eorder_currency\x18\a \x01(\tR\rorderCurrency\x12+\n" +
	"\x11settlement_amount\x18\b \x01(\x01R\x10settlementAmount\x12/\n" +
	"\x13settlement_currency\x18\t \x01(\tR\x12settlementCurrency\x12%\n" +
	"\x0epayment_amount\x18\n" +
	" \x01(\x01R\rpaymentAmount\x12)\n" +
	"\x10payment_currency\x18\v \x01(\tR\x0fpaymentCurrency\x12.\n" +
	"\x13order_exchange_rate\x18\f \x01(\x01R\x11orderExchangeRate\x122\n" +
	"\x15payment_exchange_rate\x18\r \x01(\x01R\x13paymentExchangeRate\x12\x1a\n" +
	"\bprovider\x18\x0e \x01(\tR\bprovider\x12!\n" +
	"\fchannel_code\x18\x0f \x01(\tR\vchannelCode\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x10 \x01(\x04R\tchannelId\x12.\n" +
	"\x13merchant_account_id\x18\x11 \x01(\x04R\x11merchantAccountId\x12.\n" +
	"\x13provider_payment_id\x18\x12 \x01(\tR\x11providerPaymentId\x12!\n" +
	"\fcheckout_url\x18\x13 \x01(\tR\vcheckoutUrl\x12\x16\n" +
	"\x06status\x18\x14 \x01(\tR\x06status\x12%\n" +
	"\x0efailure_reason\x18\x15 \x01(\tR\rfailureReason\x12#\n" +
	"\rmetadata_json\x18\x16 \x01(\tR\fmetadataJson\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x17 \x01(\tR\texpiresAt\x12\x1d\n" +
	"\n" +
	"created_at\x18\x18 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x19 \x01(\tR\tupdatedAt\x12\x1b\n" +
	"\ttenant_id\x18\x1a \x01(\tR\btenantId\x122\n" +
	"\x15gateway_connection_id\x18\x1b \x01(\x04R\x13gatewayConnectionId2\xd4\a\n" +
	"\x0ePaymentService\x12]\n" +
	"\x12CreatePaymentOrder\x12%.payment.v1.CreatePaymentOrderRequest\x1a .payment.v1.PaymentOrderResponse\x12W\n" +
	"\x0fGetPaymentOrder\x12\".payment.v1.GetPaymentOrderRequest\x1a .payment.v1.PaymentOrderResponse\x12u\n" +
	"\x1eGetPaymentOrderByMerchantOrder\x121.payment.v1.GetPaymentOrderByMerchantOrderRequest\x1a .payment.v1.PaymentOrderResponse\x12Y\n" +
	"\x11QueryPaymentOrder\x12\".payment.v1.GetPaymentOrderRequest\x1a .payment.v1.PaymentOrderResponse\x12\x81\x01\n" +
	"\x1cCheckPaymentOrderByPaymentNo\x12/.payment.v1.CheckPaymentOrderByPaymentNoRequest\x1a0.payment.v1.CheckPaymentOrderByPaymentNoResponse\x12Z\n" +
	"\x12CancelPaymentOrder\x12\".payment.v1.GetPaymentOrderRequest\x1a .payment.v1.PaymentOrderResponse\x12`\n" +
	"\x11ListPaymentOrders\x12$.payment.v1.ListPaymentOrdersRequest\x1a%.payment.v1.ListPaymentOrdersResponse\x12r\n" +
	"\x17ListSupportedCurrencies\x12*.payment.v1.ListSupportedCurrenciesRequest\x1a+.payment.v1.ListSupportedCurrenciesResponse\x12\x81\x01\n" +
	"\x1cListAvailablePaymentChannels\x12/.payment.v1.ListAvailablePaymentChannelsRequest\x1a0.payment.v1.ListAvailablePaymentChannelsResponseB\x1eZ\x1cxpayment-sdk/proto;paymentv1b\x06proto3"

var (
	file_proto_payment_proto_rawDescOnce sync.Once
	file_proto_payment_proto_rawDescData []byte
)

func file_proto_payment_proto_rawDescGZIP() []byte {
	file_proto_payment_proto_rawDescOnce.Do(func() {
		file_proto_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_payment_proto_rawDesc), len(file_proto_payment_proto_rawDesc)))
	})
	return file_proto_payment_proto_rawDescData
}

var file_proto_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_payment_proto_goTypes = []any{
	(*CreatePaymentOrderRequest)(nil),             // 0: payment.v1.CreatePaymentOrderRequest
	(*GetPaymentOrderRequest)(nil),                // 1: payment.v1.GetPaymentOrderRequest
	(*GetPaymentOrderByMerchantOrderRequest)(nil), // 2: payment.v1.GetPaymentOrderByMerchantOrderRequest
	(*CheckPaymentOrderByPaymentNoRequest)(nil),   // 3: payment.v1.CheckPaymentOrderByPaymentNoRequest
	(*CheckPaymentOrderByPaymentNoResponse)(nil),  // 4: payment.v1.CheckPaymentOrderByPaymentNoResponse
	(*ListPaymentOrdersRequest)(nil),              // 5: payment.v1.ListPaymentOrdersRequest
	(*ListPaymentOrdersResponse)(nil),             // 6: payment.v1.ListPaymentOrdersResponse
	(*ListSupportedCurrenciesRequest)(nil),        // 7: payment.v1.ListSupportedCurrenciesRequest
	(*ListSupportedCurrenciesResponse)(nil),       // 8: payment.v1.ListSupportedCurrenciesResponse
	(*ListAvailablePaymentChannelsRequest)(nil),   // 9: payment.v1.ListAvailablePaymentChannelsRequest
	(*AvailablePaymentChannel)(nil),               // 10: payment.v1.AvailablePaymentChannel
	(*ListAvailablePaymentChannelsResponse)(nil),  // 11: payment.v1.ListAvailablePaymentChannelsResponse
	(*PaymentOrderResponse)(nil),                  // 12: payment.v1.PaymentOrderResponse
}
var file_proto_payment_proto_depIdxs = []int32{
	12, // 0: payment.v1.CheckPaymentOrderByPaymentNoResponse.order:type_name -> payment.v1.PaymentOrderResponse
	12, // 1: payment.v1.ListPaymentOrdersResponse.items:type_name -> payment.v1.PaymentOrderResponse
	10, // 2: payment.v1.ListAvailablePaymentChannelsResponse.items:type_name -> payment.v1.AvailablePaymentChannel
	0,  // 3: payment.v1.PaymentService.CreatePaymentOrder:input_type -> payment.v1.CreatePaymentOrderRequest
	1,  // 4: payment.v1.PaymentService.GetPaymentOrder:input_type -> payment.v1.GetPaymentOrderRequest
	2,  // 5: payment.v1.PaymentService.GetPaymentOrderByMerchantOrder:input_type -> payment.v1.GetPaymentOrderByMerchantOrderRequest
	1,  // 6: payment.v1.PaymentService.QueryPaymentOrder:input_type -> payment.v1.GetPaymentOrderRequest
	3,  // 7: payment.v1.PaymentService.CheckPaymentOrderByPaymentNo:input_type -> payment.v1.CheckPaymentOrderByPaymentNoRequest
	1,  // 8: payment.v1.PaymentService.CancelPaymentOrder:input_type -> payment.v1.GetPaymentOrderRequest
	5,  // 9: payment.v1.PaymentService.ListPaymentOrders:input_type -> payment.v1.ListPaymentOrdersRequest
	7,  // 10: payment.v1.PaymentService.ListSupportedCurrencies:input_type -> payment.v1.ListSupportedCurrenciesRequest
	9,  // 11: payment.v1.PaymentService.ListAvailablePaymentChannels:input_type -> payment.v1.ListAvailablePaymentChannelsRequest
	12, // 12: payment.v1.PaymentService.CreatePaymentOrder:output_type -> payment.v1.PaymentOrderResponse
	12, // 13: payment.v1.PaymentService.GetPaymentOrder:output_type -> payment.v1.PaymentOrderResponse
	12, // 14: payment.v1.PaymentService.GetPaymentOrderByMerchantOrder:output_type -> payment.v1.PaymentOrderResponse
	12, // 15: payment.v1.PaymentService.QueryPaymentOrder:output_type -> payment.v1.PaymentOrderResponse
	4,  // 16: payment.v1.PaymentService.CheckPaymentOrderByPaymentNo:output_type -> payment.v1.CheckPaymentOrderByPaymentNoResponse
	12, // 17: payment.v1.PaymentService.CancelPaymentOrder:output_type -> payment.v1.PaymentOrderResponse
	6,  // 18: payment.v1.PaymentService.ListPaymentOrders:output_type -> payment.v1.ListPaymentOrdersResponse
	8,  // 19: payment.v1.PaymentService.ListSupportedCurrencies:output_type -> payment.v1.ListSupportedCurrenciesResponse
	11, // 20: payment.v1.PaymentService.ListAvailablePaymentChannels:output_type -> payment.v1.ListAvailablePaymentChannelsResponse
	12, // [12:21] is the sub-list for method output_type
	3,  // [3:12] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_payment_proto_init() }
func file_proto_payment_proto_init() {
	if File_proto_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_payment_proto_rawDesc), len(file_proto_payment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_payment_proto_goTypes,
		DependencyIndexes: file_proto_payment_proto_depIdxs,
		MessageInfos:      file_proto_payment_proto_msgTypes,
	}.Build()
	File_proto_payment_proto = out.File
	file_proto_payment_proto_goTypes = nil
	file_proto_payment_proto_depIdxs = nil
}
