// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: proto/payment.proto

package paymentv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PaymentService_CreatePaymentOrder_FullMethodName             = "/payment.v1.PaymentService/CreatePaymentOrder"
	PaymentService_GetPaymentOrder_FullMethodName                = "/payment.v1.PaymentService/GetPaymentOrder"
	PaymentService_GetPaymentOrderByMerchantOrder_FullMethodName = "/payment.v1.PaymentService/GetPaymentOrderByMerchantOrder"
	PaymentService_QueryPaymentOrder_FullMethodName              = "/payment.v1.PaymentService/QueryPaymentOrder"
	PaymentService_CheckPaymentOrderByPaymentNo_FullMethodName   = "/payment.v1.PaymentService/CheckPaymentOrderByPaymentNo"
	PaymentService_CancelPaymentOrder_FullMethodName             = "/payment.v1.PaymentService/CancelPaymentOrder"
	PaymentService_ListPaymentOrders_FullMethodName              = "/payment.v1.PaymentService/ListPaymentOrders"
	PaymentService_ListSupportedCurrencies_FullMethodName        = "/payment.v1.PaymentService/ListSupportedCurrencies"
	PaymentService_ListAvailablePaymentChannels_FullMethodName   = "/payment.v1.PaymentService/ListAvailablePaymentChannels"
)

// PaymentServiceClient is the client API for PaymentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PaymentServiceClient interface {
	CreatePaymentOrder(ctx context.Context, in *CreatePaymentOrderRequest, opts ...grpc.CallOption) (*PaymentOrderResponse, error)
	GetPaymentOrder(ctx context.Context, in *GetPaymentOrderRequest, opts ...grpc.CallOption) (*PaymentOrderResponse, error)
	GetPaymentOrderByMerchantOrder(ctx context.Context, in *GetPaymentOrderByMerchantOrderRequest, opts ...grpc.CallOption) (*PaymentOrderResponse, error)
	QueryPaymentOrder(ctx context.Context, in *GetPaymentOrderRequest, opts ...grpc.CallOption) (*PaymentOrderResponse, error)
	CheckPaymentOrderByPaymentNo(ctx context.Context, in *CheckPaymentOrderByPaymentNoRequest, opts ...grpc.CallOption) (*CheckPaymentOrderByPaymentNoResponse, error)
	CancelPaymentOrder(ctx context.Context, in *GetPaymentOrderRequest, opts ...grpc.CallOption) (*PaymentOrderResponse, error)
	ListPaymentOrders(ctx context.Context, in *ListPaymentOrdersRequest, opts ...grpc.CallOption) (*ListPaymentOrdersResponse, error)
	ListSupportedCurrencies(ctx context.Context, in *ListSupportedCurrenciesRequest, opts ...grpc.CallOption) (*ListSupportedCurrenciesResponse, error)
	ListAvailablePaymentChannels(ctx context.Context, in *ListAvailablePaymentChannelsRequest, opts ...grpc.CallOption) (*ListAvailablePaymentChannelsResponse, error)
}

type paymentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPaymentServiceClient(cc grpc.ClientConnInterface) PaymentServiceClient {
	return &paymentServiceClient{cc}
}

func (c *paymentServiceClient) CreatePaymentOrder(ctx context.Context, in *CreatePaymentOrderRequest, opts ...grpc.CallOption) (*PaymentOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PaymentOrderResponse)
	err := c.cc.Invoke(ctx, PaymentService_CreatePaymentOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) GetPaymentOrder(ctx context.Context, in *GetPaymentOrderRequest, opts ...grpc.CallOption) (*PaymentOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PaymentOrderResponse)
	err := c.cc.Invoke(ctx, PaymentService_GetPaymentOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) GetPaymentOrderByMerchantOrder(ctx context.Context, in *GetPaymentOrderByMerchantOrderRequest, opts ...grpc.CallOption) (*PaymentOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PaymentOrderResponse)
	err := c.cc.Invoke(ctx, PaymentService_GetPaymentOrderByMerchantOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) QueryPaymentOrder(ctx context.Context, in *GetPaymentOrderRequest, opts ...grpc.CallOption) (*PaymentOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PaymentOrderResponse)
	err := c.cc.Invoke(ctx, PaymentService_QueryPaymentOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) CheckPaymentOrderByPaymentNo(ctx context.Context, in *CheckPaymentOrderByPaymentNoRequest, opts ...grpc.CallOption) (*CheckPaymentOrderByPaymentNoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckPaymentOrderByPaymentNoResponse)
	err := c.cc.Invoke(ctx, PaymentService_CheckPaymentOrderByPaymentNo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) CancelPaymentOrder(ctx context.Context, in *GetPaymentOrderRequest, opts ...grpc.CallOption) (*PaymentOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PaymentOrderResponse)
	err := c.cc.Invoke(ctx, PaymentService_CancelPaymentOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) ListPaymentOrders(ctx context.Context, in *ListPaymentOrdersRequest, opts ...grpc.CallOption) (*ListPaymentOrdersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPaymentOrdersResponse)
	err := c.cc.Invoke(ctx, PaymentService_ListPaymentOrders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) ListSupportedCurrencies(ctx context.Context, in *ListSupportedCurrenciesRequest, opts ...grpc.CallOption) (*ListSupportedCurrenciesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSupportedCurrenciesResponse)
	err := c.cc.Invoke(ctx, PaymentService_ListSupportedCurrencies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) ListAvailablePaymentChannels(ctx context.Context, in *ListAvailablePaymentChannelsRequest, opts ...grpc.CallOption) (*ListAvailablePaymentChannelsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAvailablePaymentChannelsResponse)
	err := c.cc.Invoke(ctx, PaymentService_ListAvailablePaymentChannels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaymentServiceServer is the server API for PaymentService service.
// All implementations must embed UnimplementedPaymentServiceServer
// for forward compatibility.
type PaymentServiceServer interface {
	CreatePaymentOrder(context.Context, *CreatePaymentOrderRequest) (*PaymentOrderResponse, error)
	GetPaymentOrder(context.Context, *GetPaymentOrderRequest) (*PaymentOrderResponse, error)
	GetPaymentOrderByMerchantOrder(context.Context, *GetPaymentOrderByMerchantOrderRequest) (*PaymentOrderResponse, error)
	QueryPaymentOrder(context.Context, *GetPaymentOrderRequest) (*PaymentOrderResponse, error)
	CheckPaymentOrderByPaymentNo(context.Context, *CheckPaymentOrderByPaymentNoRequest) (*CheckPaymentOrderByPaymentNoResponse, error)
	CancelPaymentOrder(context.Context, *GetPaymentOrderRequest) (*PaymentOrderResponse, error)
	ListPaymentOrders(context.Context, *ListPaymentOrdersRequest) (*ListPaymentOrdersResponse, error)
	ListSupportedCurrencies(context.Context, *ListSupportedCurrenciesRequest) (*ListSupportedCurrenciesResponse, error)
	ListAvailablePaymentChannels(context.Context, *ListAvailablePaymentChannelsRequest) (*ListAvailablePaymentChannelsResponse, error)
	mustEmbedUnimplementedPaymentServiceServer()
}

// UnimplementedPaymentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPaymentServiceServer struct{}

func (UnimplementedPaymentServiceServer) CreatePaymentOrder(context.Context, *CreatePaymentOrderRequest) (*PaymentOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePaymentOrder not implemented")
}
func (UnimplementedPaymentServiceServer) GetPaymentOrder(context.Context, *GetPaymentOrderRequest) (*PaymentOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPaymentOrder not implemented")
}
func (UnimplementedPaymentServiceServer) GetPaymentOrderByMerchantOrder(context.Context, *GetPaymentOrderByMerchantOrderRequest) (*PaymentOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPaymentOrderByMerchantOrder not implemented")
}
func (UnimplementedPaymentServiceServer) QueryPaymentOrder(context.Context, *GetPaymentOrderRequest) (*PaymentOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryPaymentOrder not implemented")
}
func (UnimplementedPaymentServiceServer) CheckPaymentOrderByPaymentNo(context.Context, *CheckPaymentOrderByPaymentNoRequest) (*CheckPaymentOrderByPaymentNoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckPaymentOrderByPaymentNo not implemented")
}
func (UnimplementedPaymentServiceServer) CancelPaymentOrder(context.Context, *GetPaymentOrderRequest) (*PaymentOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelPaymentOrder not implemented")
}
func (UnimplementedPaymentServiceServer) ListPaymentOrders(context.Context, *ListPaymentOrdersRequest) (*ListPaymentOrdersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPaymentOrders not implemented")
}
func (UnimplementedPaymentServiceServer) ListSupportedCurrencies(context.Context, *ListSupportedCurrenciesRequest) (*ListSupportedCurrenciesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSupportedCurrencies not implemented")
}
func (UnimplementedPaymentServiceServer) ListAvailablePaymentChannels(context.Context, *ListAvailablePaymentChannelsRequest) (*ListAvailablePaymentChannelsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAvailablePaymentChannels not implemented")
}
func (UnimplementedPaymentServiceServer) mustEmbedUnimplementedPaymentServiceServer() {}
func (UnimplementedPaymentServiceServer) testEmbeddedByValue()                        {}

// UnsafePaymentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PaymentServiceServer will
// result in compilation errors.
type UnsafePaymentServiceServer interface {
	mustEmbedUnimplementedPaymentServiceServer()
}

func RegisterPaymentServiceServer(s grpc.ServiceRegistrar, srv PaymentServiceServer) {
	// If the following call panics, it indicates UnimplementedPaymentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PaymentService_ServiceDesc, srv)
}

func _PaymentService_CreatePaymentOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePaymentOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).CreatePaymentOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_CreatePaymentOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).CreatePaymentOrder(ctx, req.(*CreatePaymentOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_GetPaymentOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPaymentOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).GetPaymentOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_GetPaymentOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).GetPaymentOrder(ctx, req.(*GetPaymentOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_GetPaymentOrderByMerchantOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPaymentOrderByMerchantOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).GetPaymentOrderByMerchantOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_GetPaymentOrderByMerchantOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).GetPaymentOrderByMerchantOrder(ctx, req.(*GetPaymentOrderByMerchantOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_QueryPaymentOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPaymentOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).QueryPaymentOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_QueryPaymentOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).QueryPaymentOrder(ctx, req.(*GetPaymentOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_CheckPaymentOrderByPaymentNo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckPaymentOrderByPaymentNoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).CheckPaymentOrderByPaymentNo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_CheckPaymentOrderByPaymentNo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).CheckPaymentOrderByPaymentNo(ctx, req.(*CheckPaymentOrderByPaymentNoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_CancelPaymentOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPaymentOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).CancelPaymentOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_CancelPaymentOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).CancelPaymentOrder(ctx, req.(*GetPaymentOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_ListPaymentOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPaymentOrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).ListPaymentOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_ListPaymentOrders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).ListPaymentOrders(ctx, req.(*ListPaymentOrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_ListSupportedCurrencies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSupportedCurrenciesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).ListSupportedCurrencies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_ListSupportedCurrencies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).ListSupportedCurrencies(ctx, req.(*ListSupportedCurrenciesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_ListAvailablePaymentChannels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAvailablePaymentChannelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).ListAvailablePaymentChannels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_ListAvailablePaymentChannels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).ListAvailablePaymentChannels(ctx, req.(*ListAvailablePaymentChannelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PaymentService_ServiceDesc is the grpc.ServiceDesc for PaymentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PaymentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "payment.v1.PaymentService",
	HandlerType: (*PaymentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePaymentOrder",
			Handler:    _PaymentService_CreatePaymentOrder_Handler,
		},
		{
			MethodName: "GetPaymentOrder",
			Handler:    _PaymentService_GetPaymentOrder_Handler,
		},
		{
			MethodName: "GetPaymentOrderByMerchantOrder",
			Handler:    _PaymentService_GetPaymentOrderByMerchantOrder_Handler,
		},
		{
			MethodName: "QueryPaymentOrder",
			Handler:    _PaymentService_QueryPaymentOrder_Handler,
		},
		{
			MethodName: "CheckPaymentOrderByPaymentNo",
			Handler:    _PaymentService_CheckPaymentOrderByPaymentNo_Handler,
		},
		{
			MethodName: "CancelPaymentOrder",
			Handler:    _PaymentService_CancelPaymentOrder_Handler,
		},
		{
			MethodName: "ListPaymentOrders",
			Handler:    _PaymentService_ListPaymentOrders_Handler,
		},
		{
			MethodName: "ListSupportedCurrencies",
			Handler:    _PaymentService_ListSupportedCurrencies_Handler,
		},
		{
			MethodName: "ListAvailablePaymentChannels",
			Handler:    _PaymentService_ListAvailablePaymentChannels_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/payment.proto",
}
